# Generated by Django 3.2 on 2024-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
