# Generated by Django 3.2 on 2024-09-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='home_group',
            new_name='student',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student', models.ManyToManyField(to='authentications.Student')),
            ],
        ),
    ]
