# Generated by Django 3.2 on 2024-09-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_auto_20240906_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.CharField(max_length=20),
        ),
    ]
